### ISSUE TITLE
ansible-review import issue

### ISSUE THREAD

**Issue by mjohno** [willthames/ansible-review#11]
I encountered the following issue when running ansible-review:

```
$ ansible-review
/apps/tools/pip/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Traceback (most recent call last):
  File "/apps/tools/pip/bin/ansible-review", line 8, in <module>
    from ansiblereview.version import __version__
  File "/apps/tools/pip/lib/python2.6/site-packages/ansiblereview/__init__.py", line 6, in <module>
    import utils
  File "/apps/tools/pip/lib/python2.6/site-packages/ansiblereview/utils/__init__.py", line 12, in <module>
    import importlib
ImportError: No module named importlib
```
As you can guess this is on python2.6.6.

It seems that installing ansible-review via pip doesn't install importlib. Should this dependency exist?

Installing import lib via pip seems to have resolved the issue.

**Comment by willthames** [comment]
hint: should be a simple PR to fix this

would be good to have a tox test that checks this too.

**Comment by willthames** [comment]
Fixed by #13

**Comment by willthames** [comment]
I am having major problems getting ansible-review to pass tests with python-2.6

Are you unable to run ansible-review on a RHEL7 host or similar?

I don't really plan to support python-2.6, although MRs that pass all existing tests are welcomed. My attempts so far are on the travis_fix branch. I'll probably role master back to including the importlib but not including the 2.6 tox tests so that travis actually passes.

**Comment by mjohno** [comment]
Not yet. Will try with software collections. Don't worry about the 2.6
support.
